const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function openLead(){const m=$('#leadModal');if(!m)return;m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}
function closeLead(){const m=$('#leadModal');if(!m)return;m.classList.remove('open');m.setAttribute('aria-hidden','true');document.body.style.overflow='';}
window.openLead=openLead;window.closeLead=closeLead;
$$('.js-book').forEach(b=>b.addEventListener('click',openLead));
window.addEventListener('keydown',e=>{if(e.key==='Escape'){closeLead();closeLightbox();}});
window.addEventListener('scroll',()=>$('#header')?.classList.toggle('scrolled',scrollY>30),{passive:true});
if('IntersectionObserver' in window){const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');o.unobserve(e.target)}}),{threshold:.08});$$('.reveal').forEach(x=>o.observe(x));}else $$('.reveal').forEach(x=>x.classList.add('visible'));
const lb=$('#lightbox'), lbi=$('#lightboxImage'), lbc=$('#lightboxCaption');
function openLightbox(img){if(!lb)return;lbi.src=img.currentSrc||img.src;lbi.alt=img.alt||'';lbc.textContent=img.alt||'';lb.classList.add('open');lb.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}
function closeLightbox(){if(!lb)return;lb.classList.remove('open');lb.setAttribute('aria-hidden','true');document.body.style.overflow='';setTimeout(()=>{if(!lb.classList.contains('open'))lbi.src=''},150)}
window.closeLightbox=closeLightbox; $$('.lightboxable').forEach(img=>img.addEventListener('click',()=>openLightbox(img)));$('.lightbox-close')?.addEventListener('click',closeLightbox);lb?.addEventListener('click',e=>{if(e.target===lb)closeLightbox()});
function youtubeEmbed(url){if(!url)return '';try{const u=new URL(url);let id=u.searchParams.get('v');if(u.hostname.includes('youtu.be'))id=u.pathname.slice(1);if(u.pathname.includes('/embed/'))id=u.pathname.split('/embed/')[1].split('/')[0];return id?`https://www.youtube-nocookie.com/embed/${id}?rel=0&modestbranding=1`:''}catch{return ''}}
function whatsappUrl(number){const wa=(number||'').replace(/\D/g,'');return wa?`https://wa.me/${wa}?text=${encodeURIComponent('Hola, quiero recibir información de Costella Telchac Residencial.')}`:'#';}
function applyAdminOverrides(){try{const d=JSON.parse(localStorage.getItem('costella_admin_v3')||localStorage.getItem('costella_admin_v2')||'{}');const set=(sel,key)=>{if(d[key]!==undefined&&$(sel))$(sel).textContent=d[key]};set('.hero h1','heroTitle');set('.hero .lead','heroLead');set('#intro h2','introTitle');set('#intro .intro-copy>p:last-child','introBody');set('#telchac h2','telchacTitle');set('#telchac .location-copy>p:not(.eyebrow)','telchacBody');set('#costella h2','costellaTitle');set('#galeria h2','galleryTitle');set('#video h2','videoTitle');set('#video .video-head>p','videoBody');set('#amenidades h2','amenitiesTitle');set('#club-stella h2','clubTitle');set('#club-stella .feature-content>p:not(.eyebrow)','clubBody');set('#terreno h2','commercialTitle');set('#terreno .reveal>p:not(.eyebrow)','commercialBody');set('.history-grid h2','historyTitle');set('.history-grid .reveal>p:not(.eyebrow):not(.disclaimer)','historyBody');set('.faq h2','faqTitle');set('.closing h2','closingTitle');const vals=$$('.commercial-data strong');if(d.apartado&&vals[0])vals[0].textContent=d.apartado;if(d.enganche&&vals[1])vals[1].textContent=d.enganche;if(d.financiamiento&&vals[2])vals[2].textContent=d.financiamiento;if(d.mensualidades&&vals[3])vals[3].textContent=d.mensualidades;const imgs=d.images||{};if(imgs.hero)$('#top .hero-media').src=imgs.hero;if(imgs.intro1)$$('#intro img')[0].src=imgs.intro1;if(imgs.intro2)$$('#intro img')[1].src=imgs.intro2;if(imgs.intro3)$$('#intro img')[2].src=imgs.intro3;if(imgs.location)$('#telchac .location-visual>img').src=imgs.location;if(imgs.club)$('#club-stella .feature-media').src=imgs.club;if(imgs.closing)$$('.closing .feature-media')[0].src=imgs.closing;const embed=youtubeEmbed(d.youtube||COSTELLA_CONFIG.youtubeUrl);if(embed){const f=$('#youtubeFrame'),p=$('.video-placeholder');f.src=embed;f.hidden=false;p.hidden=true}COSTELLA_CONFIG.bookingUrl=d.booking||COSTELLA_CONFIG.bookingUrl;COSTELLA_CONFIG.whatsappNumber=d.whatsapp||COSTELLA_CONFIG.whatsappNumber;COSTELLA_CONFIG.leadEndpoint=d.leadEndpoint||COSTELLA_CONFIG.leadEndpoint;COSTELLA_CONFIG.metaPixelId=d.pixel||COSTELLA_CONFIG.metaPixelId;}catch(e){console.warn(e)}}
applyAdminOverrides();
const fw=$('#floatingWhatsapp');if(fw)fw.href=whatsappUrl(COSTELLA_CONFIG.whatsappNumber);
$('#leadForm')?.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));if(COSTELLA_CONFIG.leadEndpoint){try{await fetch(COSTELLA_CONFIG.leadEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,source:'costella-landing'})})}catch(err){console.warn(err)}}if(COSTELLA_CONFIG.metaPixelId&&window.fbq)fbq('track','Lead');$('#bookingLink').href=COSTELLA_CONFIG.bookingUrl||'#';$('#whatsappLink').href=whatsappUrl(COSTELLA_CONFIG.whatsappNumber);$('#leadFormView').hidden=true;$('#successView').hidden=false;});
